version: 2

models:
  - name: stg_users
    description: Information on all users
    columns:
      - name: user_id
        tests:
          - not_null
  - name: stg_orders
    description: Information on all orders
    columns:
      - name: order_id
        tests:
          - not_null
  - name: stg_products
    description: Information on all products
    columns:
      - name: product_id
        tests:
          - not_null
      - name: name
      - name: price
        tests:
          - not_null
          - positive_values
      - name: quantity
        tests:
          - not_null
          - positive_values
  - name: stg_promos
    description: Information on all promos
    columns:
      - name: promo_id
        tests:
          - not_null
      - name: discount
        tests:
          - percentage_values
      - name: status
  - name: stg_addresses
    description: Information on all addresses
    columns:
      - name: address_id
        tests:
          - not_null
  - name: stg_order_items
    description: Information on all order items
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null