version: 2

models:
  - name: stg_users
    description: Information on all users
    columns:
      - name: user_id
        tests:
          - not_null
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: created_at
      - name: updated_at
      - name: address_id
  - name: stg_orders
    description: Information on all orders
    columns:
      - name: order_id
        tests:
          - not_null
      - name: promo_id
      - name: user_id
      - name: address_id
      - name: created_at
      - name: order_cost
      - name: shipping_cost
      - name: order_total
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status
  - name: stg_products
    description: Information on all products
    columns:
      - name: product_id
        tests:
          - not_null
      - name: name
      - name: price
        tests:
          - not_null
          - positive_values
      - name: quantity
        tests:
          - not_null
          - positive_values
  - name: stg_promos
    description: Information on all promos
    columns:
      - name: promo_id
        tests:
          - not_null
      - name: discount
        tests:
          - percentage_values
      - name: status